steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/quick-read-wizard:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/quick-read-wizard:latest',
      '.'
    ]

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/quick-read-wizard:$COMMIT_SHA']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/quick-read-wizard:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'quick-read-wizard',
      '--image', 'gcr.io/$PROJECT_ID/quick-read-wizard:$COMMIT_SHA',
      '--region', 'asia-south1',  # Changed to Asia South (Mumbai)
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '4Gi',  # Increased for Playwright + AI processing
      '--cpu', '2',
      '--timeout', '900',  # Increased timeout for large file processing
      '--concurrency', '10',  # Reduced for memory-intensive operations
      '--max-instances', '10',  # Reduced to control costs
      '--min-instances', '0',  # Allow scaling to zero
      '--set-env-vars', 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_REGION=asia-south1',
      '--port', '8080'
    ]

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/quick-read-wizard:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/quick-read-wizard:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY